from database import db
from models.user import Institution, User, ActivityLog
from utils.response import api_response, api_error
from datetime import datetime

class InstitutionService:
    def __init__(self):
        pass

    def request_institution(self, data):
        name = data.get('name')
        email = data.get('email') # This will be admin_email
        institution_code = data.get('institution_code') # Optional during request? Usually generated by admin.

        if not all([name, email]):
            return api_error("Name and email are required.", code=400)

        if Institution.query.filter_by(admin_email=email).first():
            return api_error("Email already in use.", code=409)

        # Generate a temporary code if not provided
        import secrets
        import string
        if not institution_code:
            institution_code = ''.join(secrets.choice(string.ascii_uppercase + string.digits) for _ in range(8))

        new_inst = Institution(
            name=name,
            admin_email=email,
            institution_code=institution_code,
            status='pending'
        )

        try:
            db.session.add(new_inst)
            db.session.commit()
            return api_response(message="Institution request submitted.", data=new_inst.to_dict(), code=201)
        except Exception as e:
            db.session.rollback()
            return api_error(f"Failed to submit request: {str(e)}", code=500)

    def validate_code(self, code):
        inst = Institution.query.filter_by(institution_code=code).first()
        if not inst:
            return api_error("Invalid code.", code=404)
        if inst.status != 'approved':
            return api_error("Institution not approved.", code=403)
        
        admin_count = User.query.filter_by(institution_id=inst.id, role='admin').count()
        staff_count = User.query.filter_by(institution_id=inst.id, role='staff').count()
        
        return api_response(data={
            "valid": True,
            "institution_name": inst.name,
            "admin_count": admin_count,
            "staff_count": staff_count
        })

    def get_all_institutions(self):
        institutions = Institution.query.all()
        return [inst.to_dict() for inst in institutions]

    def approve_institution(self, institution_id):
        inst = Institution.query.get(institution_id)
        if not inst:
            return api_error("Institution not found", code=404)
            
        try:
            inst.status = 'approved'
            db.session.commit()
            return api_response(message="Institution approved.", data=inst.to_dict())
        except Exception as e:
            db.session.rollback()
            return api_error(f"Approval failed: {str(e)}", code=500)

    def reject_institution(self, institution_id, reason):
        inst = Institution.query.get(institution_id)
        if not inst:
            return api_error("Institution not found", code=404)
        try:
            inst.status = 'rejected'
            db.session.commit()
            return api_response(message="Institution rejected.")
        except Exception as e:
            db.session.rollback()
            return api_error("Failed to reject institution", code=500)
